q = Queue()
print(q.isEmpty()) 
q.enqueue(10)
q.enqueue(20)
q.enqueue(30)
print(q.size())  
print(q.front())  
print(q.dequeue())  
print(q.dequeue())  
print(q.size())  
print(q.isEmpty()) 
